#ifndef BKS_MERLINSTYLE
  #define BKS_MERLINSTYLE   0x0800
#endif

#ifndef PP_PAGEBACKGROUNDCOLOR
  #define PP_PAGEBACKGROUNDCOLOR   69L
#endif

#define APP_ICON                    5

#define DOWN_BITMAP                 10
#define UP_BITMAP                   11

#define CVR_FRAME                   50
#define CVR_BITMAP                  51
#define CVR_FONTPALETTE             52
#define CVR_COLORPALETTE            53
#define CVR_HICOLORPALETTE          54
#define CVR_SYSTEMOBJECT            55
#define CVR_MOUSEOBJECT             56
#define CVR_SYSTEMSETUP             57
#define CVR_BITMAP2                 58

#define MSE_FRAME                   100
#define MSE_M1NONE                  101
#define MSE_M1SHIFT                 102
#define MSE_M1CTRL                  103
#define MSE_M1SHIFTCTRL             104
#define MSE_M1ALT                   105
#define MSE_M1SHIFTALT              106
#define MSE_M1CTRLALT               107
#define MSE_M1ALL                   108
#define MSE_M2NONE                  109
#define MSE_M2SHIFT                 110
#define MSE_M2CTRL                  111
#define MSE_M2SHIFTCTRL             112
#define MSE_M2ALT                   113
#define MSE_M2SHIFTALT              114
#define MSE_M2CTRLALT               115
#define MSE_M2ALL                   116
#define MSE_M3NONE                  117
#define MSE_M3SHIFT                 118
#define MSE_M3CTRL                  119
#define MSE_M3SHIFTCTRL             120
#define MSE_M3ALT                   121
#define MSE_M3SHIFTALT              122
#define MSE_M3CTRLALT               123
#define MSE_M3ALL                   124
#define MSE_ICON                    125
#define MSE_ABOUT                   126
#define MSE_EXIT                    127
#define MSE_DISABLED                128
#define MSE_NOTASKLIST              129
#define MSE_RELOAD                  130
#define MSE_MORE                    131
#define MSE_HELP                    132
#define MSE_CLIP                    133
#define MSE_CLEAR                   135
#define MSE_CMDLINE                 136
#define MSE_VIRTUAL                 137
#define MSE_CALC                    138
#define MSE_FM2                     139
#define MSE_OPEN                    140
#define MSE_MINALL                  141
#define MSE_SAVESCREEN              142
#define MSE_SWITCH                  143
#define MSE_SNAPSHOTS               144
#define MSE_CLIPS                   145
#define MSE_EXIT2                   146
#define MSE_LAUNCHPAD               147
#define MSE_DOSCMDLINE              148
#define MSE_LOWMEMORY               149

#define RUN_FRAME                   200
#define RUN_FIND                    201
#define RUN_NAME                    202
#define RUN_DIR                     203
#define RUN_ARGS                    204
#define RUN_DIRHDR                  205
#define RUN_ARGSHDR                 206

#define MSA_FRAME                   300
#define MSA_CLOCK                   301
#define MSA_DATE                    302
#define MSA_VIRTUAL                 303
#define MSA_RESET                   304
#define MSA_SHIFTBUMP               305
#define MSA_BUMPDESKS               306
#define MSA_EDITEXCLUDE             307
#define MSA_USECLIPMGR              308
#define MSA_CHORDS                  309
#define MSA_MOUSEMINS               310
#define MSA_SAVESCREEN              311
#define MSA_SWAPMON                 312
#define MSA_SWAPFLOAT               313
#define MSA_HELP                    314
#define MSA_SLIDINGFOCUS            315
#define MSA_NOZORDER                316
#define MSA_WRAPSCREEN              317
#define MSA_CRNR                    318
#define MSA_SCRNFLDR                319
#define MSA_DELAY                   320
#define MSA_ENHANCEFILEDLG          321
#define MSA_EDITFEXCLUDE            322
#define MSA_CLIPSAVE                323
#define MSA_MOVEMOUSE               324
#define MSA_DEFBUTTON               325
#define MSA_CENTERDLG               326
#define MSA_CLIPSFLDR               327
#define MSA_NONORMALIZE             328
#define MSA_SCRNBITCOUNT            329
#define MSA_CONFIRMEXIT             330
#define MSA_ENHANCETITLEBARS        331
#define MSA_TITLEBAREDIT            332
#define MSA_HARDMON                 333
#define MSA_AMPM                    334
#define MSA_SAVEACTIVE              335
#define MSA_VIRTTEXT                336
#define MSA_NOVIRTWPS               337
#define MSA_TICKS                   338
#define MSA_CPUMON                  339
#define MSA_NOMONCLICK              340
#define MSA_AVERAGE                 341
#define MSA_MEMORY                  342
#define MSA_RUNAHEAD                343
#define MSA_TITLEBARMENUS           344
#define MSA_EXTRATITLEBARMENUS      345
#define MSA_SHOWFREEINMENUS         346
#define MSA_FRACTIONS               347
#define MSA_CLIPMON                 348
#define MSA_CLIPAPPEND              349
#define MSA_PMEMORY                 350
#define MSA_SHOWSWAPFREE            351
#define MSA_PROCESS                 352

#define CPU_FRAME                   490
#define CPU_RESET                   491
#define CPU_PULSE                   492
#define CPU_KILLPROC                493
#define CPU_HARDWARE                494

#define SWAP_FRAME                  495
#define SWAP_LAUNCHPAD              496
#define SWAP_WARPCENTER             497
#define SWAP_CONNECTIONS            498
#define SWAP_INFO                   499
#define SWAP_SETTINGS               500
#define SWAP_SYSTEM                 501
#define SWAP_TEMPS                  502
#define SWAP_FM2                    503

#define CLOCK_FRAME                 505
#define CLOCK_SETTINGS              506
#define CLOCK_CLOCK                 507
#define CLOCK_VIRTUAL               508
#define CLOCK_SWITCHLIST            509
#define CLOCK_CLIPBOARD             510
#define CLOCK_CALCULATOR            511
#define CLOCK_CMDLINE               512

#define DESK_FRAME                  515

#define HARD_FRAME                  520
#define HARD_OPEN                   521
#define HARD_VDIR                   522
#define HARD_CHKDSK                 523
#define HARD_FM2                    524
#define HARD_C                      530

#define BIG_FRAME                   560
#define VRT_1                       561
#define VRT_2                       562
#define VRT_3                       563
#define VRT_4                       564
#define VRT_5                       565
#define VRT_6                       566
#define VRT_7                       567
#define VRT_8                       568
#define VRT_9                       569

#define CAP_FRAME                   580

#define CRNR_FRAME                  600
#define CRNR_LISTBOX                601
#define CRNR_TOPLEFT                602
#define CRNR_TOPRIGHT               603
#define CRNR_BOTLEFT                604
#define CRNR_BOTRIGHT               605
#define CRNR_HELP                   606

#define CRD_FRAME                   650
#define CRD_PATH                    651

#define CLC_FRAME                   699
#define CLC_DUMMY                   700
#define CLC_HELP                    720
#define CLC_RESULTS                 721
#define CLC_ADD                     722
#define CLC_SUB                     723
#define CLC_MUL                     724
#define CLC_DIV                     725
#define CLC_EQ                      726
#define CLC_MADD                    727
#define CLC_MSUB                    728
#define CLC_MMUL                    729
#define CLC_MDIV                    730
#define CLC_MCLR                    731
#define CLC_CLR                     732
#define CLC_ECLR                    733
#define CLC_DECIMAL                 734
#define CLC_MREC                    735
#define CLC_PASTE                   736
#define CLC_COPY                    737

#define TTL_FRAME                   800
#define TTL_REDSLIDER               801
#define TTL_REDENTRY                802
#define TTL_GREENSLIDER             803
#define TTL_GREENENTRY              804
#define TTL_BLUESLIDER              805
#define TTL_BLUEENTRY               806
#define TTL_REDESLIDER              807
#define TTL_REDEENTRY               808
#define TTL_GREENESLIDER            809
#define TTL_GREENEENTRY             810
#define TTL_BLUEESLIDER             811
#define TTL_BLUEEENTRY              812
#define TTL_FAKETITLEBAR            813
#define TTL_VERTICAL                814
#define TTL_CENTERED                815
#define TTL_STEPS                   816
#define TTL_STARTOREND              817
#define TTL_HELP                    818
#define TTL_APPLY                   819
#define TTL_UNDO                    820
#define TTL_BORDER                  821
#define TTL_GROUPSTART              822
#define TTL_GROUPEND                823
#define TTL_LISTBOX                 824
#define TTL_ADDSCHEME               825
#define TTL_DELSCHEME               826
#define TTL_SCHEMENAME              827
#define TTL_SCHEMEPROG              828
#define TTL_STARTCOLOR              829
#define TTL_ENDCOLOR                830
#define TTL_SCHEMETITLE             831
#define TTL_EXCLUDE                 832
#define TTL_UP                      833
#define TTL_DOWN                    834
#define TTL_BITMAPNAME              835
#define TTL_USEBITMAP               836
#define TTL_FINDBITMAP              837
#define TTL_INVERTGRAD              838
#define TTL_TEXTURE                 839
#define TTL_CLOCKINTITLEBARS        840

#define CLP_FRAME                   900
#define CLP_APPEND                  901
#define CLP_CLEAR                   902

#define MEM_FRAME                   910

#define TSK_FRAME                   920

#define MSC_FRAME                   950
#define MSC_MSEINTASKLIST           951

#define MS1_FRAME                   1000
#define MS1_AUTODROP                1001

#define MS2_FRAME                   1100
#define MS2_VIEWER                  1101
#define MS2_CONFIRMDIRDEL           1102
#define MS2_CONFIRMFILEDEL          1103
#define MS2_REMEMBER                1104
#define MS2_REMEMBERF               1105
#define MS2_AGGRESSIVE              1106
#define MS2_EDITOR                  1107

#define MS3_FRAME                   1200
#define MS4_FRAME                   1300
#define MS5_FRAME                   1400
#define MS5_EDITAFTER               1401

#define MS6_FRAME                   1500

#define MS7_FRAME                   1600
#define MS7_BITMAP                  1601
                                        
#define NTE_FRAME                   2800
#define NTE_NOTEBOOK                2801

#define IDM_MENU1                   2999
#define IDM_MENU2                   3999
#define IDM_MENU3                   4999
#define IDM_MENU4                   5999
#define IDM_MENU5                   6999
#define IDM_MENU6                   7999
#define IDM_MENU7                   8999
#define IDM_TASK                    9999
#define IDM_HANDICAP                29999

#define IDM_CLIPTEXT                30999
#define IDM_SAVECLIP                32000
#define IDM_LOADCLIP                32001
#define IDM_SAVECLIP2               32002
#define IDM_SAVEBIT                 32003
#define IDM_LOADBIT                 32004
#define IDM_SAVEBIT2                32005
#define IDM_SAVEMET                 32006
#define IDM_LOADMET                 32007
#define IDM_SAVEMET2                32008
#define IDM_BITINFO                 32009
#define IDM_BITINFO2                32010
#define IDM_APPENDCLIP              32011
#define IDM_APPENDCLIP2             32012
#define IDM_CLIPFOLDER              32013

#define IDM_CLIPHELP                32098
#define IDM_CLEARCLIP               32099
#define IDM_SHOWTEXT2               32100
#define IDM_SHOWBIT2                32101
#define IDM_SHOWMET                 32102
#define IDM_SHOWMET2                32103
#define IDM_CLIPSAVEALL             32104
#define IDM_CLIPLOADALL             32105
#define IDM_CLIPAUTOSAVE            32106

#define CLIP_FRAME                  32766

