#include <stdlib.h>

#pragma data_seg(DATAN)

        char *cmdnames[] = {"OS/2 default",
                            "Show MSE",
                            "*Close window",
                            "Close window",
                            "*Window to back",
                            "Window to back",
                            "*Window on screen",
                            "Window on screen",
                            "*Roll up/down",
                            "Roll up/down",
                            "*Move window",
                            "Move window",
                            "*Size window",
                            "Size window",
                            "*Maximize window",
                            "Maximize window",
                            "*Minimize window",
                            "Minimize window",
                            "Window list",
                            "Switch list",
                            "Next window",
                            "B1 2-click",
                            "B1+2 chord",
                            "Win text->clip",
                            "Win text->clip append",
                            "Clip->win text",
                            "Start FM/2",
                            "Open object",
                            "Minimize all",
                            "Menu #1",
                            "Menu #2",
                            "Menu #3",
                            "Menu #4",
                            "Menu #5",
                            "Menu #6",
                            "Menu #7",
                            "Virtual desktops",
                            "Clipboard manager",
                            "Calculator",
                            "OS/2 command line",
                            "Scrollbar",
                            "Pick click",
                            NULL};

        char *crnrnames[] = {"Nothing",
                             "Show MSE",
                             "Switch list",
                             "Open object",
                             "Menu #1",
                             "Menu #2",
                             "Menu #3",
                             "Menu #4",
                             "Menu #5",
                             "Menu #6",
                             "Menu #7",
                             "Virtual desktops",
                             "Clipboard manager",
                             "Calculator",
                             NULL};

        char *objwinclass = "MSEOBJWINDOW",
             *gobjwinclass = "MSEGOBJWINDOW",
             *graphwinclass = "MSEGRAPHWINDOW",
             *helvtext = "8.Helv",
             *defopen = "OPEN=DEFAULT",
             *setopen = "OPEN=SETTINGS",
             *eexe = "E.EXE",
             *clipwinclass = "MSECLIPWINDOW",
             *deskwinclass = "MSEDESKWINDOW",
             *shelvtext = "7.Helv",
             *clipmgr = "MSE clipboard manager",
             *desknoteclass = "MSEDESKNOTE",
             *monwinclass = "MSEMONITOR",
             *objwinclass2 = "MSEOBJWINDOW2",
             *objwinclass3 = "MSEOBJWINDOW3",
             *objwinclass4 = "MSEOBJWINDOW4",
             *appname = "MSE";
